feat: yatt-id enhancements
- colored ouput (for fzf)
- new "-m" flat (returns comma separated values)
- new "theme" command for themes selecting

diff --git a/shell/yatt-id b/shell/yatt-id
--- a/shell/yatt-id
+++ b/shell/yatt-id
@@ -1,6 +1,7 @@
 #!/bin/sh
-fzf=${YATT_FZF:="fzf"}
-usage_prefix=${yatt_script_usage_prefix:="Get id of yatt's record"}
+fzf=${YATT_FZF:="fzf --ansi"}
+fzfm=${YATT_FZF_MULTI:="fzf --ansi -m"}
+
 script_executable=${yatt_script_executable:=$0}
 
 usage () {
@@ -15,8 +16,12 @@ USAGE:
 SUBCOMMANDS:
     task        Handles tasks
     group       Handles groups
-    interval    Handles intervals
+    interval    Handles intervalsa
+    theme       Handles themes
     help        Prints this message
+
+FLAGS:
+    -m          Multiselect
 "
   exit 0
 }
@@ -29,12 +34,40 @@ error () {
 
 [ -z "$1" ] && usage
 [ "$1" != "help" ] || usage
-echo $1 | grep -E '^task|interval|group$' > /dev/null || error
 
-command=$1s
-command=${command/groups/"tasks -g"}
+command=$1
+if [ "$command" == "-m" ]; then
+  command=$2
+  fzf=$fzfm
+fi
 
-line=$(yatt -c list $command | $fzf)
-line="${line%%]*}"
+echo $command | grep -E '^task|interval|group|theme$' > /dev/null || error
 
-echo "${line#[}"
+if [ "$command" == "theme" ]; then
+  command="themes list"
+
+  while read -r line; do
+    line=$(echo $line | grep -E '[0-9a-z\-]+' -o)
+    if [ "$res" != "" ]; then
+      res="$res,$line"
+    else
+      res="$line"
+    fi
+  done <<< $(yatt $command | $fzf)
+else
+  command=${command}s
+  command="list ${command/groups/"tasks -g"}"
+
+  while read -r line; do
+    line="${line%%]*}"
+    line="${line#[}"
+    if [ "$res" != "" ]; then
+      res="$res,$line"
+    else
+      res="$line"
+    fi
+  done <<< $(yatt $command | $fzf)
+fi
+
+
+echo "${res#[}"
